name: HSV2_nextstrain_analysis
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - augur>=25.0.0
  - auspice>=2.55.0
  - emboss
  - jupyterlab
  - nextstrain-cli
  - pandas
  - seaborn
  - snakemake