name: HSV2_nextstrain_analysis
channels:
  - conda-forge
  - bioconda

dependencies:
  - augur
  - auspice
  - emboss
  - jupyterlab
  - nextstrain-cli
  - pandas
  - seaborn
  - snakemake